webserver:
  base_url: http://127.0.0.1:8080
  timeout: 30

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  virtual_host: /

auth_service:
  base_url: http://localhost:8080
  timeout: 30
  secret_key: key